export type ErrorCode =
  | "VALIDATION_ERROR"
  | "UNAUTHENTICATED"
  | "FORBIDDEN"
  | "TENANT_ACCESS_DENIED"
  | "SUBSCRIPTION_NOT_FOUND"
  | "EXECUTION_NOT_FOUND"
  | "DEAD_LETTER_NOT_FOUND"
  | "DEAD_LETTER_ALREADY_RESOLVED"
  | "EXECUTION_NOT_REDRIVABLE"
  | "IDEMPOTENCY_KEY_REUSED"
  | "CATALOG_UNAVAILABLE"
  | "SUBSCRIPTION_SERVICE_UNAVAILABLE"
  | "PUBLICATION_SERVICE_UNAVAILABLE"
  | "INVALID_SCHEDULE_CONFIG"
  | "CONCURRENT_MODIFICATION"
  | "INTERNAL_ERROR";

const STATUS_BY_CODE: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 400,
  UNAUTHENTICATED: 401,
  FORBIDDEN: 403,
  TENANT_ACCESS_DENIED: 403,
  SUBSCRIPTION_NOT_FOUND: 404,
  EXECUTION_NOT_FOUND: 404,
  DEAD_LETTER_NOT_FOUND: 404,
  DEAD_LETTER_ALREADY_RESOLVED: 409,
  EXECUTION_NOT_REDRIVABLE: 409,
  IDEMPOTENCY_KEY_REUSED: 409,
  CATALOG_UNAVAILABLE: 503,
  SUBSCRIPTION_SERVICE_UNAVAILABLE: 503,
  PUBLICATION_SERVICE_UNAVAILABLE: 503,
  INVALID_SCHEDULE_CONFIG: 422,
  CONCURRENT_MODIFICATION: 409,
  INTERNAL_ERROR: 500,
};

export class AppError extends Error {
  readonly code: ErrorCode;
  readonly statusCode: number;

  constructor(code: ErrorCode, message: string) {
    super(message);
    this.name = "AppError";
    this.code = code;
    this.statusCode = STATUS_BY_CODE[code];
  }
}
