-- Normalized immutable operational events (spec section 6/7). event_id is
-- the SOURCE's own idempotent identifier (whatever the push envelope or
-- poller/normalizer assigned it) — never generated by this table — so
-- `INSERT ... ON CONFLICT (event_id) DO NOTHING` is the entire dedup
-- mechanism for duplicate/late/replayed events.
CREATE TABLE operational_events (
    event_id VARCHAR(128) PRIMARY KEY,
    event_type VARCHAR(64) NOT NULL,

    organization_id VARCHAR(64) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,

    -- Nullable: an event may be persisted before correlation resolves which
    -- execution it belongs to is not possible here (correlation always runs
    -- before persist in the ingestion pipeline), but kept nullable for
    -- forward-compatibility with any future async-correlation path.
    execution_id VARCHAR(64) REFERENCES operational_executions (execution_id),

    data_product_id VARCHAR(128) NOT NULL,
    product_version VARCHAR(32) NOT NULL,

    stage VARCHAR(30) CHECK (
        stage IS NULL OR stage IN (
            'EXCHANGE_RECEIVED', 'EXCHANGE_VALIDATION', 'BRONZE_INGESTION',
            'SILVER_TRANSFORMATION', 'GOLD_PRODUCT_BUILD', 'QUALITY_VALIDATION',
            'PUBLICATION', 'OUTBOUND_EXCHANGE', 'FILE_DELIVERY', 'API_DELIVERY'
        )
    ),
    status VARCHAR(20) CHECK (
        status IS NULL OR status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'RETRYING', 'BLOCKED', 'LATE', 'CANCELLED', 'UNKNOWN')
    ),
    attempt_number INTEGER NOT NULL DEFAULT 1,
    duration_ms BIGINT,

    source_service VARCHAR(64) NOT NULL,
    source_entity_type VARCHAR(64),
    source_entity_id VARCHAR(128),

    correlation_id VARCHAR(64),
    trace_id VARCHAR(64),

    occurred_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Never customer row-level data (spec section 6) — enforced by the
    -- normalizer allowlist, not by the database.
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX ix_operational_events_execution ON operational_events (execution_id);
CREATE INDEX ix_operational_events_tenant_product_time ON operational_events (tenant_id, data_product_id, occurred_at DESC);
