export type ErrorCode =
  | "VALIDATION_ERROR"
  | "UNAUTHENTICATED"
  | "FORBIDDEN"
  | "TENANT_ACCESS_DENIED"
  | "ENTITLEMENT_NOT_FOUND"
  | "PRODUCT_NOT_ENTITLED"
  | "ENTITLEMENT_EXPIRED"
  | "ENTITLEMENT_DENIED"
  | "SUBSCRIPTION_NOT_FOUND"
  | "SUBSCRIPTION_ALREADY_EXISTS"
  | "INVALID_SUBSCRIPTION_STATE"
  | "INVALID_STATE_TRANSITION"
  | "PRODUCT_NOT_FOUND"
  | "PRODUCT_NOT_ACTIVE"
  | "PRODUCT_VERSION_NOT_FOUND"
  | "VERSION_POLICY_NOT_RESOLVABLE"
  | "DELIVERY_METHOD_NOT_SUPPORTED"
  | "FILE_FORMAT_NOT_SUPPORTED"
  | "INVALID_DELIVERY_PREFERENCE"
  | "CATALOG_UNAVAILABLE"
  | "IDEMPOTENCY_KEY_REUSED"
  | "CONCURRENT_MODIFICATION"
  | "INTERNAL_ERROR";

const STATUS_BY_CODE: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 400,
  UNAUTHENTICATED: 401,
  FORBIDDEN: 403,
  TENANT_ACCESS_DENIED: 403,
  ENTITLEMENT_NOT_FOUND: 404,
  PRODUCT_NOT_ENTITLED: 403,
  ENTITLEMENT_EXPIRED: 403,
  ENTITLEMENT_DENIED: 403,
  SUBSCRIPTION_NOT_FOUND: 404,
  SUBSCRIPTION_ALREADY_EXISTS: 409,
  INVALID_SUBSCRIPTION_STATE: 409,
  INVALID_STATE_TRANSITION: 409,
  PRODUCT_NOT_FOUND: 404,
  PRODUCT_NOT_ACTIVE: 409,
  PRODUCT_VERSION_NOT_FOUND: 404,
  VERSION_POLICY_NOT_RESOLVABLE: 422,
  DELIVERY_METHOD_NOT_SUPPORTED: 422,
  FILE_FORMAT_NOT_SUPPORTED: 422,
  INVALID_DELIVERY_PREFERENCE: 400,
  CATALOG_UNAVAILABLE: 503,
  IDEMPOTENCY_KEY_REUSED: 409,
  CONCURRENT_MODIFICATION: 409,
  INTERNAL_ERROR: 500,
};

export class AppError extends Error {
  readonly code: ErrorCode;
  readonly statusCode: number;

  constructor(code: ErrorCode, message: string) {
    super(message);
    this.name = "AppError";
    this.code = code;
    this.statusCode = STATUS_BY_CODE[code];
  }
}
